# Site settings
title: Sahand Zeinali
description: Developer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sahand Zeinali
user_description: Natural Language Processing & Machine Learning
user_title: Developer
email: szeinali@hawk.iit.edu
twitter_username: TheSandCloud
linkedin_username: szeinali
github_username:  szeinali
instagram_username: sandcloud


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
