
title: My Resume
url: 'http://szeinali.com'
# baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Sahand Zeinali  ## put your name
title: 'SOFTWARE DESIGNER &amp; RESEARCHER'  ## your title
location: Chicago , USA


## Social Profiles
# facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com/TheSandCloud  ## your twitter account url
github: http://www.github.com/szeinali  ## your github account url
linkedin: http://www.linkedin.com/in/szeinali  ## your linkedin account url
# dribbble: http://www.dribble.com  ## you dribbble account url
# foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
